### ISSUE TITLE
Style guide?

### ISSUE THREAD

**Issue by tokyoincode** [tokyoincode/bookit#3]
Hey guys, just wanted to ask, which style guide do you follow?

**Comment by 6temes** [comment]
We use this one:

https://github.com/bbatsov/rails-style-guide

But basically, what we do is to lint the code with **Rubocop** with almost the standard configuration. That way, none of us have to care about enforcing the rules on the commits of developers.

We use **Guard** while we are developing to automatically run **Rspec** and **Rubocop** in each file we modify. Also, in our Github repository is connected with **CircleCI** and **SideCI**, so every time we push a commit to production, the code is tested and linted.

**Comment by tokyoincode** [comment]
Hi Daniel!

Thank you! Sounds interesting, will take a quick look into Guard and Robocop a little later on.
