### ISSUE TITLE
Fixtures vs. Factories

### ISSUE THREAD

**Issue by tokyoincode** [tokyoincode/bookit#4]
Hey guys!

I have another question. Have been reading a lot about TDD in Rails and what some of the best practices are.

From what I understand, there seems to be a lot of debate between using fixtures vs. factories for setting up test data (ex. a test user)

I like the idea of using factories (with FactoryGirl). However, some argue that fixtures and factories are both bad. 

What is your take on this?

Will use factories for testing for now, seems a lot more explicit.

Thanks!

**Comment by 6temes** [comment]
Hi, 

I am really sorry. I apparently missed the github notification for this issue. :/

Can you assign it to me next time? That will reduce the possibilities of me missing it...

We use FactoryGirl. In my opinion, they are a really convenient way to keep the code that create the data for the examples out of the test. Specially when you have many models connected.

Compare:

```
product = Product.new(....)
order = Order.new(........)
line_item = LineItem.new(.....)
payment = Payent.new(....)
```

With:

```
FactoryGirl.create :order, :completed
```

Of course, everybody is entitled to an opinion. :P

**Comment by tokyoincode** [comment]
Hello Daniel,

Sure, no problem! Sorry about that. Thanks for answering.

Using FactoryGirl and it's really nice. I agree, factories are a lot easier to understand and work with. Will test it out some more.
